[tool.poetry]
name = "cryptomathtrade"
version = "0.1.0"
description = ""
authors = ["T_X <treider.xylioner@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
